---
title: "Avnnet"
author: "Diego Candela Salomón"
date: "13/9/2020"
output:
  pdf_document: default
  html_document: default
---

#Avnnet

En este documento mostramos la implementación y entrenamiento de dos modelos entrenados con caret de avnnet. 

Los paquetes que se utilizaron son los siguientes:

```
library(caret)
library(dplyr)

```
Para esta parte del análisis se ha diseñado una función muy simple. Dado que los parámetros de entrenamiento se han encontrado a través de ensayo y error, se requería una función con la que averiguar rápidamente la eficacia del modelo previo a construir una matriz de confusión.

La función aciertos_avnnet requiere de un argumento:

* df: un dataframe que contiene en la primera columna las etiquetas objetivo y en la segunda columna las predicciones resultantes del modelo. 

La función devuelve un dataframe con una columna codificada en Verdadero/Falso para averiguar rápidamente los aciertos del modelo. 

```
aciertos_avnnet <- function(df){
  df<- as.data.frame(df)
  df$Aciertos <- F
  for (i in 1:length(df$Aciertos)){
    if ((df[i,1] == df[i,2])){
      df[i,3] <- T
    }
  }
  return(df)
}
```
El paquete caret permite entrenar modelos de avnnet que son modelos de redes neuronales promediadas. Primero importaremos el dataset previo a la partida y después el dataset completo. Entrenaremos dos modelos.

Primero realizamos la importación de los datasets data_train, data_test y sus correspondientes etiquetas. Hacemos un cbind del data_train con sus etiquetas.

```
data_train         <- readRDS("./datosPreGame/data_train")
data_test          <- readRDS("./datosPreGame/data_test")
labels_data_train  <- readRDS("./datosPreGame/labels_train")
labels_data_test   <- readRDS("./datosPreGame/labels_test")

data_train <- cbind(labels_data_train, data_train)

```
Los modelos de avnnet suelen tener problemas cuando trabajan con muchos predictores binarios, especialmente cuando la varianza de muchos de estos predictores es próxima a cero. Con este motivo, el paquete caret incluye una función "nearZeroVar" que genera un índice de predictores que cumplen estas características y que han de ser eliminados de dataset para que el modelo se calcule correctamente. 

```
indiceCerosTrain <- nearZeroVar(data_train)

data_train       <- data_train[,-indiceCerosTrain]
```
##Preparando caret

Una vez el dataset está listo procedemos a establecer los parámetros de caret. A lo largo de los distintos modelos que se han generado en las pruebas de este trabajo, estos son los parámetros escogidos.

```
grupos=4
sinicio=1234
repe=3
size=c(5)
decay=c(0.01)
repeticiones=3
itera=100

```
Y ahora establecemos los parámetros de control, el grid y el entrenamiento del modelo.

```
control<-trainControl(method = "repeatedcv",number=grupos,repeats=repe,
                      savePredictions = "all",classProbs=TRUE) 

# Aplico caret y construyo modelo

avnnetgrid <-  expand.grid(size=size,decay=decay,bag=FALSE)

avnnet_1<- train(make.names(labels_data_train)~.,
               data=data_train,
               method="avNNet",
               linout = FALSE,
               maxit=itera,
               repeats=repeticiones,
               trControl=control,
               tuneGrid=avnnetgrid,
               trace=T)

```
Una vez se ha entrenado el modelo se ha de poner a prueba frente al data_test. Los resultados están expuestos en el documento principal de este proyecto.

Primero aplicamos el mismo índice de la función "nearZeroVar" al set de testeo y luego utilizamos la función del paquete base de R "predict".

Guardamos esas predicciones en un dataframe para generar la matriz de confusión con la función proporcionada por el paquete caret. 

Con el fin de asegurar que no ha habido ningún cambio de formato y que el vector predictions tiene los mismos niveles que las etiquetas del data_test añadimos la linea 110 y generamos la matriz de confusión. 

```
data_test <- cbind(labels_data_test, data_test)
data_test <- data_test[,-indiceCerosTrain]
data_test <- data_test[,-1]

predictions  <- predict(avnnet_1, data_test)
predicciones <- as.data.frame(cbind(labels_data_test, predictions))

levels(predictions) <- c("0","1")

matriz_confusion<- confusionMatrix(data=predictions, reference = labels_data_test)

```
Una vez obtenemos la matriz de confusión, averiguamos el RMSE para valorar el modelo en su conjunto en la comparación con el resto de modelos incluidos en este trabajo

```
residuals_preGame <- as.numeric(labels_data_test) - as.numeric(predictions)
RMSE_preGame      <- sqrt(mean(residuals_preGame^2))

```



Una vez queda calculado el modelo, eliminamos del entorno de trabajo tanto data_train y data_test para importar las versiones completas

```
rm(data_train,data_test)

```

Importamos las versiones completas de los respectivos datasets

```
data_train         <- readRDS("./datosCompleto/data_train")
data_test          <- readRDS("./datosCompleto/data_test")

data_train       <- cbind(labels_data_train, data_train)
indiceCerosTrain <- nearZeroVar(data_train)
data_train       <- data_train[,-indiceCerosTrain]

```

Y volvemos a entrenar el modelo respetando los mismos parámetros para la comparación final

```
control<-trainControl(method = "repeatedcv",number=grupos,repeats=repe,
                      savePredictions = "all",classProbs=TRUE) 

avnnetgrid <-  expand.grid(size=size,decay=decay,bag=FALSE)

avnnet_2<- train(make.names(labels_data_train)~.,
               data=data_train,
               method="avNNet",
               linout = FALSE,
               maxit=itera,
               repeats=repeticiones,
               trControl=control,
               tuneGrid=avnnetgrid,
               trace=T)

```
Volvemos a realizar el mismo proceso para extraer las predicciones, la matriz de confusión
y el RMSE

```
data_test <- cbind(labels_data_test, data_test)
data_test <- data_test[,-indiceCerosTrain]
data_test <- data_test[,-1]

predictions  <- predict(avnnet_2, data_test)
predicciones <- as.data.frame(cbind(labels_data_test, predictions))

levels(predictions) <- c("0","1")

matriz_confusion<- confusionMatrix(data=predictions, reference = labels_data_test)

residuals_completo <- as.numeric(labels_data_test) - as.numeric(predictions)
RMSE_completo      <- sqrt(mean(residuals_completo^2))

```

